spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/develop?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
  jpa:
    hibernate:
      ddl-auto: update