spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/develop?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
qiniu:
  AccessKey: your_qiniu_AccessKey
  SecretKey: your_qiniu_SecretKey
  Bucket: your_qiniu_bucket
  URL_PREFIX: the_domain_name_your_qiniu_bucket_used